<<<<<<< HEAD
app = "noxo-backend"
primary_region = "lax"

[env]
PORT = "3001"

[build]
builder = "paketobuildpacks/builder:base"

[[services]]
internal_port = 3001
protocol = "tcp"

  [[services.ports]]
  handlers = ["http"]
  port = 80

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443
=======
# fly.toml app configuration file generated for noxo-backend-broken-surf-8388 on 2025-07-16T07:32:13-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'noxo-backend-broken-surf-8388'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
>>>>>>> 865297188b33778ee0043fc41823c9663ae65614
