
const express = require('express');
const cors = require('cors');
const app = express();
const db = require('./db');
const { startJobWorker } = require('./jobProcessor');

// Middleware
app.use(cors({ origin: '*' }));
app.use(express.json());

// Core routes
const vaultRoutes = require('./routes/vault');
const ritualRoutes = require('./routes/ritual');
const jobRoutes = require('./routes/jobs');
const userRoutes = require('./routes/user');
const leaderboardRoutes = require('./routes/leaderboard');
const nodeRoutes = require('./routes/nodes');
const warRoutes = require('./routes/war');
const logRoutes = require('./routes/logs');
const pingRoutes = require('./routes/ping');
const testRoutes = require('./routes/test');

app.use('/api/vault', vaultRoutes);
app.use('/api/ritual', ritualRoutes);
app.use('/api/jobs', jobRoutes);
app.use('/api/user', userRoutes);
app.use('/api/leaderboard', leaderboardRoutes);
app.use('/api/nodes', nodeRoutes);
app.use('/api/war', warRoutes);
app.use('/api/logs', logRoutes);
app.use('/api/ping', pingRoutes);
app.use('/api/test', testRoutes);

// Vaultcore routes
const vaultContributions = require('./vaultcore/vaultContributions');
app.get('/api/vaultContributions', (req, res) => res.json({ status: 'OK', module: 'vaultContributions' }));
const vaultForecast = require('./vaultcore/vaultForecast');
app.get('/api/vaultForecast', (req, res) => res.json({ status: 'OK', module: 'vaultForecast' }));
const vaultLock = require('./vaultcore/vaultLock');
app.get('/api/vaultLock', (req, res) => res.json({ status: 'OK', module: 'vaultLock' }));
const vaultMood = require('./vaultcore/vaultMood');
app.get('/api/vaultMood', (req, res) => res.json({ status: 'OK', module: 'vaultMood' }));
const vaultRewards = require('./vaultcore/vaultRewards');
app.get('/api/vaultRewards', (req, res) => res.json({ status: 'OK', module: 'vaultRewards' }));
const vaultRisk = require('./vaultcore/vaultRisk');
app.get('/api/vaultRisk', (req, res) => res.json({ status: 'OK', module: 'vaultRisk' }));
const vaultSentiment = require('./vaultcore/vaultSentiment');
app.get('/api/vaultSentiment', (req, res) => res.json({ status: 'OK', module: 'vaultSentiment' }));
const war = require('./vaultcore/war');
app.get('/api/war', (req, res) => res.json({ status: 'OK', module: 'war' }));
const weather = require('./vaultcore/weather');
app.get('/api/weather', (req, res) => res.json({ status: 'OK', module: 'weather' }));
const weeklyBonuses = require('./vaultcore/weeklyBonuses');
app.get('/api/weeklyBonuses', (req, res) => res.json({ status: 'OK', module: 'weeklyBonuses' }));
const xp = require('./vaultcore/xp');
app.get('/api/xp', (req, res) => res.json({ status: 'OK', module: 'xp' }));
const xpBurst = require('./vaultcore/xpBurst');
app.get('/api/xpBurst', (req, res) => res.json({ status: 'OK', module: 'xpBurst' }));
const xplog = require('./vaultcore/xplog');
app.get('/api/xplog', (req, res) => res.json({ status: 'OK', module: 'xplog' }));
const alerts = require('./vaultcore/alerts');
app.get('/api/alerts', (req, res) => res.json({ status: 'OK', module: 'alerts' }));
const api = require('./vaultcore/api');
app.get('/api/api', (req, res) => res.json({ status: 'OK', module: 'api' }));
const burnLog = require('./vaultcore/burnLog');
app.get('/api/burnLog', (req, res) => res.json({ status: 'OK', module: 'burnLog' }));
const chaos = require('./vaultcore/chaos');
app.get('/api/chaos', (req, res) => res.json({ status: 'OK', module: 'chaos' }));
const chaosBeacon = require('./vaultcore/chaosBeacon');
app.get('/api/chaosBeacon', (req, res) => res.json({ status: 'OK', module: 'chaosBeacon' }));
const chaosButtonHistory = require('./vaultcore/chaosButtonHistory');
app.get('/api/chaosButtonHistory', (req, res) => res.json({ status: 'OK', module: 'chaosButtonHistory' }));
const chaosCodex = require('./vaultcore/chaosCodex');
app.get('/api/chaosCodex', (req, res) => res.json({ status: 'OK', module: 'chaosCodex' }));
const chaosDrift = require('./vaultcore/chaosDrift');
app.get('/api/chaosDrift', (req, res) => res.json({ status: 'OK', module: 'chaosDrift' }));
const chaosLog = require('./vaultcore/chaosLog');
app.get('/api/chaosLog', (req, res) => res.json({ status: 'OK', module: 'chaosLog' }));
const chaosMutations = require('./vaultcore/chaosMutations');
app.get('/api/chaosMutations', (req, res) => res.json({ status: 'OK', module: 'chaosMutations' }));
const chaosReplays = require('./vaultcore/chaosReplays');
app.get('/api/chaosReplays', (req, res) => res.json({ status: 'OK', module: 'chaosReplays' }));
const chaosScoreboard = require('./vaultcore/chaosScoreboard');
app.get('/api/chaosScoreboard', (req, res) => res.json({ status: 'OK', module: 'chaosScoreboard' }));
const chaosSensorGrid = require('./vaultcore/chaosSensorGrid');
app.get('/api/chaosSensorGrid', (req, res) => res.json({ status: 'OK', module: 'chaosSensorGrid' }));
const chaosTier = require('./vaultcore/chaosTier');
app.get('/api/chaosTier', (req, res) => res.json({ status: 'OK', module: 'chaosTier' }));
const codex = require('./vaultcore/codex');
app.get('/api/codex', (req, res) => res.json({ status: 'OK', module: 'codex' }));
const combo = require('./vaultcore/combo');
app.get('/api/combo', (req, res) => res.json({ status: 'OK', module: 'combo' }));
const dailyReward = require('./vaultcore/dailyReward');
app.get('/api/dailyReward', (req, res) => res.json({ status: 'OK', module: 'dailyReward' }));
const echoes = require('./vaultcore/echoes');
app.get('/api/echoes', (req, res) => res.json({ status: 'OK', module: 'echoes' }));
const forecast = require('./vaultcore/forecast');
app.get('/api/forecast', (req, res) => res.json({ status: 'OK', module: 'forecast' }));
const founder = require('./vaultcore/founder');
app.get('/api/founder', (req, res) => res.json({ status: 'OK', module: 'founder' }));
const founderPatch = require('./vaultcore/founderPatch');
app.get('/api/founderPatch', (req, res) => res.json({ status: 'OK', module: 'founderPatch' }));
const friends = require('./vaultcore/friends');
app.get('/api/friends', (req, res) => res.json({ status: 'OK', module: 'friends' }));
const globalEvent = require('./vaultcore/globalEvent');
app.get('/api/globalEvent', (req, res) => res.json({ status: 'OK', module: 'globalEvent' }));
const inviteCode = require('./vaultcore/inviteCode');
app.get('/api/inviteCode', (req, res) => res.json({ status: 'OK', module: 'inviteCode' }));
const job = require('./vaultcore/job');
app.get('/api/job', (req, res) => res.json({ status: 'OK', module: 'job' }));
const jobs = require('./vaultcore/jobs');
app.get('/api/jobs', (req, res) => res.json({ status: 'OK', module: 'jobs' }));
const leaderboard = require('./vaultcore/leaderboard');
app.get('/api/leaderboard', (req, res) => res.json({ status: 'OK', module: 'leaderboard' }));
const legacyNodes = require('./vaultcore/legacyNodes');
app.get('/api/legacyNodes', (req, res) => res.json({ status: 'OK', module: 'legacyNodes' }));
const logs = require('./vaultcore/logs');
app.get('/api/logs', (req, res) => res.json({ status: 'OK', module: 'logs' }));
const mangoAudit = require('./vaultcore/mangoAudit');
app.get('/api/mangoAudit', (req, res) => res.json({ status: 'OK', module: 'mangoAudit' }));
const mangoLeaderboard = require('./vaultcore/mangoLeaderboard');
app.get('/api/mangoLeaderboard', (req, res) => res.json({ status: 'OK', module: 'mangoLeaderboard' }));
const mangoMythos = require('./vaultcore/mangoMythos');
app.get('/api/mangoMythos', (req, res) => res.json({ status: 'OK', module: 'mangoMythos' }));
const mangoRadar = require('./vaultcore/mangoRadar');
app.get('/api/mangoRadar', (req, res) => res.json({ status: 'OK', module: 'mangoRadar' }));
const mangoVault = require('./vaultcore/mangoVault');
app.get('/api/mangoVault', (req, res) => res.json({ status: 'OK', module: 'mangoVault' }));
const mangoWarVault = require('./vaultcore/mangoWarVault');
app.get('/api/mangoWarVault', (req, res) => res.json({ status: 'OK', module: 'mangoWarVault' }));
const mangoWeather = require('./vaultcore/mangoWeather');
app.get('/api/mangoWeather', (req, res) => res.json({ status: 'OK', module: 'mangoWeather' }));
const mythicScrolls = require('./vaultcore/mythicScrolls');
app.get('/api/mythicScrolls', (req, res) => res.json({ status: 'OK', module: 'mythicScrolls' }));
const nodeAlignment = require('./vaultcore/nodeAlignment');
app.get('/api/nodeAlignment', (req, res) => res.json({ status: 'OK', module: 'nodeAlignment' }));
const nodes = require('./vaultcore/nodes');
app.get('/api/nodes', (req, res) => res.json({ status: 'OK', module: 'nodes' }));
const nodeSoul = require('./vaultcore/nodeSoul');
app.get('/api/nodeSoul', (req, res) => res.json({ status: 'OK', module: 'nodeSoul' }));
const patchNotes = require('./vaultcore/patchNotes');
app.get('/api/patchNotes', (req, res) => res.json({ status: 'OK', module: 'patchNotes' }));
const ping = require('./vaultcore/ping');
app.get('/api/ping', (req, res) => res.json({ status: 'OK', module: 'ping' }));
const profile = require('./vaultcore/profile');
app.get('/api/profile', (req, res) => res.json({ status: 'OK', module: 'profile' }));
const rankPerks = require('./vaultcore/rankPerks');
app.get('/api/rankPerks', (req, res) => res.json({ status: 'OK', module: 'rankPerks' }));
const ranks = require('./vaultcore/ranks');
app.get('/api/ranks', (req, res) => res.json({ status: 'OK', module: 'ranks' }));
const referrals = require('./vaultcore/referrals');
app.get('/api/referrals', (req, res) => res.json({ status: 'OK', module: 'referrals' }));
const requirements = require('./vaultcore/requirements');
app.get('/api/requirements', (req, res) => res.json({ status: 'OK', module: 'requirements' }));
const ritual = require('./vaultcore/ritual');
app.get('/api/ritual', (req, res) => res.json({ status: 'OK', module: 'ritual' }));
const ritualCooldown = require('./vaultcore/ritualCooldown');
app.get('/api/ritualCooldown', (req, res) => res.json({ status: 'OK', module: 'ritualCooldown' }));
const ritualGlitchLog = require('./vaultcore/ritualGlitchLog');
app.get('/api/ritualGlitchLog', (req, res) => res.json({ status: 'OK', module: 'ritualGlitchLog' }));
const ritualHistory = require('./vaultcore/ritualHistory');
app.get('/api/ritualHistory', (req, res) => res.json({ status: 'OK', module: 'ritualHistory' }));
const ritualPatchNotes = require('./vaultcore/ritualPatchNotes');
app.get('/api/ritualPatchNotes', (req, res) => res.json({ status: 'OK', module: 'ritualPatchNotes' }));
const ritualReadiness = require('./vaultcore/ritualReadiness');
app.get('/api/ritualReadiness', (req, res) => res.json({ status: 'OK', module: 'ritualReadiness' }));
const rituals = require('./vaultcore/rituals');
app.get('/api/rituals', (req, res) => res.json({ status: 'OK', module: 'rituals' }));
const roleEvolution = require('./vaultcore/roleEvolution');
app.get('/api/roleEvolution', (req, res) => res.json({ status: 'OK', module: 'roleEvolution' }));
const roles = require('./vaultcore/roles');
app.get('/api/roles', (req, res) => res.json({ status: 'OK', module: 'roles' }));
const settings = require('./vaultcore/settings');
app.get('/api/settings', (req, res) => res.json({ status: 'OK', module: 'settings' }));
const streak = require('./vaultcore/streak');
app.get('/api/streak', (req, res) => res.json({ status: 'OK', module: 'streak' }));
const strikeLog = require('./vaultcore/strikeLog');
app.get('/api/strikeLog', (req, res) => res.json({ status: 'OK', module: 'strikeLog' }));
const summonMatrix = require('./vaultcore/summonMatrix');
app.get('/api/summonMatrix', (req, res) => res.json({ status: 'OK', module: 'summonMatrix' }));
const summonmod = require('./vaultcore/summonmod');
app.get('/api/summonmod', (req, res) => res.json({ status: 'OK', module: 'summonmod' }));
const systemHealth = require('./vaultcore/systemHealth');
app.get('/api/systemHealth', (req, res) => res.json({ status: 'OK', module: 'systemHealth' }));
const test = require('./vaultcore/test');
app.get('/api/test', (req, res) => res.json({ status: 'OK', module: 'test' }));
const timeattack = require('./vaultcore/timeattack');
app.get('/api/timeattack', (req, res) => res.json({ status: 'OK', module: 'timeattack' }));
const trail = require('./vaultcore/trail');
app.get('/api/trail', (req, res) => res.json({ status: 'OK', module: 'trail' }));
const user = require('./vaultcore/user');
app.get('/api/user', (req, res) => res.json({ status: 'OK', module: 'user' }));
const vault = require('./vaultcore/vault');
app.get('/api/vault', (req, res) => res.json({ status: 'OK', module: 'vault' }));
const vaultBlessings = require('./vaultcore/vaultBlessings');
app.get('/api/vaultBlessings', (req, res) => res.json({ status: 'OK', module: 'vaultBlessings' }));

startJobWorker();

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
